/*
 *
 * Pricing service API
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.swapstech.galxy.fxtrader.client.pricing.model;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * PricingTier
 */

public class PricingTier {
	@JsonProperty("id")
	private String id;

	@JsonProperty("name")
	private String name;

	@JsonProperty("isEnabled")
	private boolean isEnabled = true;

	@JsonProperty("tierType")
	private String tierType;

	@JsonProperty("pricingItem")
	private List<PricingTierItem> pricingItem;

	@JsonProperty("createdBy")
	private String createdBy;

	@JsonProperty("creationTime")
	private LocalDateTime creationTime;

	@JsonProperty("lastUpdatedBy")
	private String lastUpdatedBy;

	@JsonProperty("lastUpdatedTime")
	private LocalDateTime lastUpdatedTime;

	public PricingTier() {
	}

	public PricingTier(String id, String name) {
		this.id = id;
		this.name = name;
	}

	@Override
	public int hashCode() {
		return Objects.hash(createdBy, creationTime, id, isEnabled, lastUpdatedBy, lastUpdatedTime, name, pricingItem,
				tierType);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PricingTier other = (PricingTier) obj;
		return Objects.equals(createdBy, other.createdBy) && Objects.equals(creationTime, other.creationTime)
				&& Objects.equals(id, other.id) && isEnabled == other.isEnabled
				&& Objects.equals(lastUpdatedBy, other.lastUpdatedBy)
				&& Objects.equals(lastUpdatedTime, other.lastUpdatedTime) && Objects.equals(name, other.name)
				&& Objects.equals(pricingItem, other.pricingItem) && tierType == other.tierType;
	}

	@Override
	public String toString() {
		return "PricingTier [id=" + id + ", name=" + name + ", isEnabled=" + isEnabled + ", tierType=" + tierType
				+ ", pricingItem=" + pricingItem + ", createdBy=" + createdBy + ", creationTime=" + creationTime
				+ ", lastUpdatedBy=" + lastUpdatedBy + ", lastUpdatedTime=" + lastUpdatedTime + "]";
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean getIsEnabled() {
		return isEnabled;
	}

	public void setEnabled(boolean isEnabled) {
		this.isEnabled = isEnabled;
	}

	public String getTierType() {
		return tierType;
	}

	public void setTierType(String tierType) {
		this.tierType = tierType;
	}

	public List<PricingTierItem> getPricingItem() {
		return pricingItem;
	}

	public void setPricingItem(List<PricingTierItem> pricingItem) {
		this.pricingItem = pricingItem;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public LocalDateTime getCreationTime() {
		return creationTime;
	}

	public void setCreationTime(LocalDateTime creationTime) {
		this.creationTime = creationTime;
	}

	public String getLastUpdatedBy() {
		return lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public LocalDateTime getLastUpdatedTime() {
		return lastUpdatedTime;
	}

	public void setLastUpdatedTime(LocalDateTime lastUpdatedTime) {
		this.lastUpdatedTime = lastUpdatedTime;
	}

	public PricingTier id(String id) {
		this.id = id;
		return this;
	}
	

}
